# Generated by Django 3.1 on 2020-09-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='selected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
