# Generated by Django 3.1 on 2020-08-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='number',
            field=models.CharField(max_length=11),
        ),
    ]
